service: my_service # NOTE: update this with your service name

provider:
  name: google
  memorySize: 256
  timeout: 60s
  project: long-walker-228011
  credentials: ./config.json

functions:
  time:
    handler: time
    events:
      - http: GET /time

# remember to run npm install to download the provider plugin.
plugins:
    - serverless-google-cloudfunctions

package:
  exclude:
    - .gitignore
    - .git/**